### ISSUE TITLE
这个json 解析出错啦，main_rewards字段直接解析成model了，应该是二维数组，不支持二维数组吗？

### ISSUE THREAD

**Issue by CoderHln** [fastcode555/Json2Dart_Null_Safety#2]
{
	"campaign_id": 10,
	"start_time": 1693972698,
	"end_time": 1701316800,
	"display_status": 1,
	"topic_3": 0,
	"topic_4": 0,
	"points": 0,
	"your_rewards": [{
		"reward_type": 7,
		"reward_value": 10,
		"raw_info": {
			"traits": {
				"card_image": "https://static.base.me/jpg/base.jpg",
				"type_name": "base"
			}
		},
		"reward_addr": "0xef1343b1CF679F99Aa962318BA269A69Ae281D0d"
	}, {
		"reward_type": 8,
		"reward_value": 20,
		"raw_info": {
			"traits": {
				"card_image": "https://static.copy.me/jpg/copy.jpg",
				"type_name": "copy"
			}
		},
		"reward_addr": ""
	}],
	"points_pic": "",
	"topic_pic": "",
	"target_reward": 0,
	"main_rewards": [
		[{
			"tp": 2,
			"amount": 10
		}, {
			"tp": 6,
			"amount": 10
		}],
		[{
			"tp": 1,
			"amount": 10
		}, {
			"tp": 6,
			"amount": 10
		}],
		[{
			"tp": 7,
			"amount": 100000
		}],
		[{
			"tp": 8,
			"amount": 8880000
		}]
	],
	"other_rewards": [
		[{
			"tp": 3,
			"amount": 10
		}],
		[{
			"tp": 4,
			"amount": 1000
		}],
		[{
			"tp": 5,
			"amount": 8880000
		}]
	]
}

**Comment by fastcode555** [comment]
现在已经增加支持了，有显示类型支持
[array_2d_test](https://github.com/fastcode555/Json2Dart_Null_Safety/blob/master/test/array_2d_test.dart)
没有显式类型，即
[array_list_test](https://github.com/fastcode555/Json2Dart_Null_Safety/blob/master/test/array_list_test.dart)
可以对比两个的区别，默认用第一种
